export const data = [
  {
    name: "Starter",
    accounts: "2 Accounts Management",
    frequency: "1 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "20,000",
  },
  {
    name: "Pro",
    accounts: "3 Accounts Management",
    frequency: "1 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "25,000",
  },
  {
    name: "Supreme",
    accounts: "4 Accounts Management",
    frequency: "1 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "30,000",
  },
  //PLUS plans below
  {
    name: "Starter Plus",
    accounts: "2 Accounts Management",
    frequency: "2 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "25,000",
  },
  {
    name: "Pro Plus",
    accounts: "3 Accounts Management",
    frequency: "2 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "30,000",
  },
  {
    name: "Supreme Plus",
    accounts: "4 Accounts Management",
    frequency: "2 Post Daily on Each",
    inboxComments: "Inbox & Comment Response",
    influencer: "Influencer Marketing",
    customerSupport: "Customer Support",
    performance: "Performance Statistics",
    price: "34,500",
  },
];
